// Stub adapter. Produces a valid PNG (solid colour, brand palette) so the
// rest of the pipeline — branding overlay, QC, upload, push — can be
// exercised without burning credits or requiring MCP integrations.
//
// Used by:
//   * `pulse-studio smoke`  — Phase 1 smoke test
//   * any adapter with --dry-run
//   * tests
//
// The PNG is hand-encoded so the studio has zero binary dependencies. For a
// real generation pipeline the Remotion / Higgsfield / Canva adapters take
// over.

import { mkdir, writeFile } from "node:fs/promises";
import { deflateSync } from "node:zlib";
import path from "node:path";
import { hashPrompt, type GenerateRequest, type GenerateOutput, type GeneratorAdapter } from "./base.js";

const RATIO_DIMENSIONS: Record<string, { w: number; h: number }> = {
  "9:16": { w: 1080, h: 1920 },
  "4:5": { w: 1080, h: 1350 },
  "1:1": { w: 1080, h: 1080 },
  "16:9": { w: 1920, h: 1080 },
  "2:3": { w: 1080, h: 1620 },
};

const PLATFORM_RATIO: Record<string, string> = {
  tiktok: "9:16",
  instagram_reel: "9:16",
  instagram_story: "9:16",
  facebook_reel: "9:16",
  youtube_short: "9:16",
  instagram_feed: "4:5",
  facebook_feed: "1:1",
  linkedin: "1:1",
  pinterest: "2:3",
  twitter_x: "16:9",
};

function crc32(buf: Buffer): number {
  let c: number;
  const table: number[] = [];
  for (let n = 0; n < 256; n++) {
    c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    crc = table[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Buffer): Buffer {
  const typeBuf = Buffer.from(type, "ascii");
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}

function hexToRgb(hex: string): [number, number, number] {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex);
  if (!m) return [60, 100, 220];
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

function encodeSolidPng(w: number, h: number, rgb: [number, number, number]): Buffer {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // color type: truecolor RGB
  ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;

  // One filter byte (0) per row + w*3 RGB bytes
  const rowSize = 1 + w * 3;
  const raw = Buffer.alloc(rowSize * h);
  for (let y = 0; y < h; y++) {
    raw[y * rowSize] = 0; // filter: None
    for (let x = 0; x < w; x++) {
      const off = y * rowSize + 1 + x * 3;
      raw[off] = rgb[0];
      raw[off + 1] = rgb[1];
      raw[off + 2] = rgb[2];
    }
  }
  const idat = deflateSync(raw);

  return Buffer.concat([
    signature,
    chunk("IHDR", ihdr),
    chunk("IDAT", idat),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

export const stubAdapter: GeneratorAdapter = {
  tool: "mcp_image", // pretends to be mcp_image so it slots into the dispatcher
  async isAvailable() {
    return true;
  },
  async generate(req: GenerateRequest): Promise<GenerateOutput> {
    const ratio = PLATFORM_RATIO[req.platform] ?? "1:1";
    const dims = RATIO_DIMENSIONS[ratio];
    // Downscale stub to a reasonable size to keep filesize small (256-tall).
    const scale = 256 / dims.h;
    const w = Math.round(dims.w * scale);
    const h = Math.round(dims.h * scale);
    const rgb = hexToRgb(req.brief.brand.palette);

    const png = encodeSolidPng(w, h, rgb);
    await mkdir(req.outputDir, { recursive: true });
    const file = path.join(req.outputDir, `stub-${req.platform}-${Date.now()}.png`);
    await writeFile(file, png);

    return {
      mediaPath: file,
      ratio,
      hasEarlyHook: true,        // by convention; stub has no real hook
      hasBurnedSubtitles: true,  // n/a for an image, kept truthy
      creditsSpent: 0,
      modelId: "stub-png",
      promptHash: hashPrompt([req.brief.workspace, req.platform, req.conceptHook]),
      toolNote: "Generated by stub adapter (no model called).",
    };
  },
};
