import type { ContentPiece, PlatformVariant } from "@pulse/types";

export const contentPieces: ContentPiece[] = [
  {
    id: "piece-1",
    workspaceId: "ws-qyro",
    externalRef: "creative-run-001",
    title: "Hook del lunes — POV 5 apps",
    format: "ugc_video",
    targetAccounts: ["acc-qyro-tt-app", "acc-qyro-ig-app"],
    buyerPersonaId: "persona-optimizador",
    campaignId: "campaign-q3",
    frameworkUsed: "ugc_15s",
    hookUsed: "POV: tienes 5 apps...",
    status: "in_review",
    qcResults: [
      { rule: "caption_length", severity: "warning", passed: true },
      { rule: "hashtag_count", severity: "warning", passed: true },
    ],
    source: "studio",
    createdAt: "2026-05-20T08:30:00Z",
    updatedAt: "2026-05-20T08:30:00Z",
  },
  {
    id: "piece-2",
    workspaceId: "ws-qyro",
    title: "Grid features — Carrusel IG",
    format: "carousel",
    targetAccounts: ["acc-qyro-ig-app"],
    buyerPersonaId: "persona-optimizador",
    campaignId: "campaign-q3",
    frameworkUsed: "feature_grid",
    status: "in_review",
    qcResults: [
      { rule: "caption_length", severity: "warning", passed: true, message: "OK 1200/2200" },
      { rule: "carousel_slides", severity: "error", passed: true, message: "8/10 slides" },
    ],
    source: "studio",
    createdAt: "2026-05-20T07:15:00Z",
    updatedAt: "2026-05-20T07:15:00Z",
  },
  {
    id: "piece-3",
    workspaceId: "ws-qyro",
    title: "Lifestyle Reel — Nike runner",
    format: "lifestyle_ad",
    targetAccounts: ["acc-qyro-fb-page", "acc-qyro-ig-app"],
    buyerPersonaId: "persona-transicion",
    campaignId: "campaign-q3",
    frameworkUsed: "lifestyle_30s",
    hookUsed: "Si tu vida es un caos, esto puede ayudar",
    status: "in_review",
    qcResults: [
      { rule: "duration", severity: "warning", passed: false, message: "33s — recortar a 30s ideal" },
    ],
    source: "studio",
    createdAt: "2026-05-20T11:00:00Z",
    updatedAt: "2026-05-20T11:00:00Z",
  },
  {
    id: "piece-4",
    workspaceId: "ws-qyro",
    title: "Demo Life Score — App Demo",
    format: "app_demo",
    targetAccounts: ["acc-qyro-tt-app", "acc-qyro-tt-latam"],
    buyerPersonaId: "persona-optimizador",
    frameworkUsed: "demo_22s",
    status: "in_review",
    qcResults: [],
    source: "studio",
    createdAt: "2026-05-19T18:00:00Z",
    updatedAt: "2026-05-19T18:00:00Z",
  },
  {
    id: "piece-5",
    workspaceId: "ws-qyro",
    title: "Testimonial — Mi Life Score subió 40 puntos",
    format: "ugc_video",
    targetAccounts: ["acc-qyro-ig-app", "acc-qyro-tt-app"],
    buyerPersonaId: "persona-optimizador",
    campaignId: "campaign-q3",
    hookUsed: "Mi Life Score subió 40 puntos en 6 semanas",
    status: "scheduled",
    qcResults: [],
    source: "studio",
    createdAt: "2026-05-19T10:00:00Z",
    updatedAt: "2026-05-19T15:00:00Z",
  },
  {
    id: "piece-6",
    workspaceId: "ws-qyro",
    title: "Post FB — Pricing claro",
    format: "post",
    targetAccounts: ["acc-qyro-fb-page"],
    status: "scheduled",
    qcResults: [],
    source: "manual",
    createdAt: "2026-05-18T14:00:00Z",
    updatedAt: "2026-05-18T14:00:00Z",
  },
  {
    id: "piece-7",
    workspaceId: "ws-qyro",
    title: "Reel — Antes/después semana 4",
    format: "reel",
    targetAccounts: ["acc-qyro-ig-app", "acc-qyro-fb-page"],
    buyerPersonaId: "persona-transicion",
    status: "published",
    qcResults: [],
    source: "studio",
    createdAt: "2026-05-13T09:00:00Z",
    updatedAt: "2026-05-15T11:00:00Z",
  },
  {
    id: "piece-8",
    workspaceId: "ws-qyro",
    title: "TikTok — Por qué Notion no es la respuesta",
    format: "ugc_video",
    targetAccounts: ["acc-qyro-tt-app"],
    buyerPersonaId: "persona-optimizador",
    status: "published",
    qcResults: [],
    source: "manual",
    createdAt: "2026-05-10T10:00:00Z",
    updatedAt: "2026-05-12T09:00:00Z",
  },
  {
    id: "piece-9",
    workspaceId: "ws-qyro",
    title: "Carrusel — Tu Life Score explicado",
    format: "carousel",
    targetAccounts: ["acc-qyro-ig-app"],
    status: "changes_requested",
    qcResults: [
      { rule: "image_quality", severity: "warning", passed: false, message: "Slide 3 está pixelada" },
    ],
    source: "studio",
    notes: "Rehacer slide 3 con resolución correcta.",
    createdAt: "2026-05-19T16:00:00Z",
    updatedAt: "2026-05-20T07:45:00Z",
  },
  // Personal
  {
    id: "piece-10",
    workspaceId: "ws-personal",
    title: "Vídeo personal — Madrid en mayo",
    format: "ugc_video",
    targetAccounts: ["acc-personal-tt"],
    status: "in_review",
    qcResults: [],
    source: "manual",
    createdAt: "2026-05-20T10:00:00Z",
    updatedAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "piece-11",
    workspaceId: "ws-personal",
    title: "Foto playa — reflexión",
    format: "image",
    targetAccounts: ["acc-personal-ig"],
    status: "published",
    qcResults: [],
    source: "manual",
    createdAt: "2026-05-15T20:00:00Z",
    updatedAt: "2026-05-16T08:00:00Z",
  },
  {
    id: "piece-12",
    workspaceId: "ws-personal",
    title: "Short YT — semana viajando",
    format: "short",
    targetAccounts: ["acc-personal-yt"],
    status: "scheduled",
    qcResults: [],
    source: "manual",
    createdAt: "2026-05-18T15:00:00Z",
    updatedAt: "2026-05-18T15:00:00Z",
  },
];

export const platformVariants: PlatformVariant[] = [
  // Piece 1 — TikTok + IG Reel
  {
    id: "var-1-tt",
    contentPieceId: "piece-1",
    workspaceId: "ws-qyro",
    socialAccountId: "acc-qyro-tt-app",
    platform: "tiktok",
    mediaType: "video",
    ratio: "9:16",
    durationS: 22,
    caption: "POV: tienes 5 apps y ninguna te dice si vas bien. Mi Life Score me lo dice de un vistazo. #productividad #lifestyle",
    hashtags: ["productividad", "lifestyle", "qyro"],
    boostEnabled: true,
    boostBudgetEur: 6,
    boostDurationDays: 3,
    boostDailyBudgetEur: 2,
    boostObjective: "VIDEO_VIEW",
    boostPlatforms: ["tiktok"],
    scheduledAt: "2026-05-23T19:00:00+02:00",
    status: "pending",
    createdAt: "2026-05-20T08:30:00Z",
  },
  {
    id: "var-1-ig",
    contentPieceId: "piece-1",
    workspaceId: "ws-qyro",
    socialAccountId: "acc-qyro-ig-app",
    platform: "instagram",
    mediaType: "video",
    ratio: "9:16",
    durationS: 22,
    caption: "POV: 5 apps y ninguna te dice si vas bien. Tu Life Score, en un solo número.",
    hashtags: ["productividad", "lifestyle"],
    boostEnabled: false,
    boostBudgetEur: 0,
    boostPlatforms: [],
    scheduledAt: "2026-05-23T19:30:00+02:00",
    status: "pending",
    createdAt: "2026-05-20T08:30:00Z",
  },
  // Piece 5 — scheduled today
  {
    id: "var-5-ig",
    contentPieceId: "piece-5",
    workspaceId: "ws-qyro",
    socialAccountId: "acc-qyro-ig-app",
    platform: "instagram",
    mediaType: "video",
    ratio: "9:16",
    durationS: 18,
    caption: "Mi Life Score subió 40 puntos en 6 semanas. Sin tocar el gym.",
    hashtags: ["lifestyle", "habitos"],
    boostEnabled: false,
    boostBudgetEur: 0,
    boostPlatforms: [],
    scheduledAt: "2026-05-20T12:00:00+02:00",
    status: "scheduled",
    createdAt: "2026-05-19T10:00:00Z",
  },
  {
    id: "var-5-tt",
    contentPieceId: "piece-5",
    workspaceId: "ws-qyro",
    socialAccountId: "acc-qyro-tt-app",
    platform: "tiktok",
    mediaType: "video",
    ratio: "9:16",
    durationS: 18,
    caption: "Mi Life Score subió 40 puntos en 6 semanas.",
    hashtags: ["lifestyle"],
    boostEnabled: true,
    boostBudgetEur: 3,
    boostDurationDays: 3,
    boostDailyBudgetEur: 1,
    boostObjective: "VIDEO_VIEW",
    boostPlatforms: ["tiktok"],
    scheduledAt: "2026-05-20T09:00:00+02:00",
    status: "scheduled",
    createdAt: "2026-05-19T10:00:00Z",
  },
  {
    id: "var-6-fb",
    contentPieceId: "piece-6",
    workspaceId: "ws-qyro",
    socialAccountId: "acc-qyro-fb-page",
    platform: "facebook",
    mediaType: "image",
    ratio: "1:1",
    caption: "Pricing claro. 4,99€/mes. 14 días gratis, sin tarjeta.",
    hashtags: [],
    boostEnabled: false,
    boostBudgetEur: 0,
    boostPlatforms: [],
    scheduledAt: "2026-05-20T21:00:00+02:00",
    status: "scheduled",
    createdAt: "2026-05-18T14:00:00Z",
  },
  // Personal
  {
    id: "var-10-tt",
    contentPieceId: "piece-10",
    workspaceId: "ws-personal",
    socialAccountId: "acc-personal-tt",
    platform: "tiktok",
    mediaType: "video",
    ratio: "9:16",
    durationS: 35,
    caption: "Mayo en Madrid. Hablo de qué he aprendido este mes.",
    hashtags: ["madrid", "reflexion"],
    boostEnabled: false,
    boostBudgetEur: 0,
    boostPlatforms: [],
    scheduledAt: "2026-05-20T19:00:00+02:00",
    status: "pending",
    createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "var-12-yt",
    contentPieceId: "piece-12",
    workspaceId: "ws-personal",
    socialAccountId: "acc-personal-yt",
    platform: "youtube",
    mediaType: "video",
    ratio: "9:16",
    durationS: 58,
    caption: "Una semana viajando — short",
    hashtags: ["travel", "shorts"],
    boostEnabled: false,
    boostBudgetEur: 0,
    boostPlatforms: [],
    scheduledAt: "2026-05-22T18:00:00+02:00",
    status: "scheduled",
    createdAt: "2026-05-18T15:00:00Z",
  },
];

export function piecesForWorkspace(workspaceId: string): ContentPiece[] {
  return contentPieces.filter((p) => p.workspaceId === workspaceId);
}

export function variantsForPiece(pieceId: string): PlatformVariant[] {
  return platformVariants.filter((v) => v.contentPieceId === pieceId);
}

export function variantsForWorkspace(workspaceId: string): PlatformVariant[] {
  return platformVariants.filter((v) => v.workspaceId === workspaceId);
}

export function pieceById(id: string): ContentPiece | undefined {
  return contentPieces.find((p) => p.id === id);
}
